# Utiliza la imagen base solicitada
FROM python:3.12-slim

# Crea el directorio de trabajo
WORKDIR /app

# Copia dependencias y las instala 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código fuente restante 
COPY . .

# Cambia los permisos para que tu usuario pueda ejecutar el código 
# Asume que main.py es el archivo de entrada
RUN chmod +x main.py

# Añade el comando de inicio 
CMD ["python", "main.py"]